#!/usr/bin/env python3
"""Emit Core2AgainPkg/ApTrampoline.h from the assembled trampoline.

Invoked by gen_ap_trampoline.sh; not meant to be run directly.  The OFF_*
defines are read back out of the .S rather than restated here, so the C view of
the page layout cannot drift from the assembly's view of it - a class of bug
that costs a machine reset per occurrence and reports nothing.
"""
import re
import sys

blob = open(sys.argv[1], 'rb').read()
src = open(sys.argv[2]).read()
offs = re.findall(r'^#define\s+OFF_(\w+)\s+\(DATA \+ (0x[0-9A-Fa-f]+)\)', src, re.M)

rows = '\n'.join(
    '  ' + ' '.join('0x%02X,' % c for c in blob[i:i + 12])
    for i in range(0, len(blob), 12)
)
defines = '\n'.join('#define AP_OFF_%-9s (AP_DATA + %s)' % (n, o) for n, o in offs)

print('''/** @file
  ApTrampoline.h - the AP startup trampoline, as bytes.

  GENERATED by scripts/gen_ap_trampoline.sh from scripts/ap_trampoline.S.
  Do not hand-edit: edit the .S and re-run the script.

  Single source of truth for the trampoline blob and the layout of its page.
  ApStartup.c uses it to start the real APs; tests/ap uses it to start one under
  QEMU, where a fault names itself instead of silently resetting the machine.
  Generating both from one .S is what stops the tested code and the shipped code
  from drifting apart.
**/

#ifndef AP_TRAMPOLINE_H_
#define AP_TRAMPOLINE_H_

//
// Layout of the trampoline page.  Mirrors the OFF_* defines in ap_trampoline.S.
//
#define AP_DATA         0xF00
%s

//
// %d bytes of position-independent real -> protected -> long mode code.
//
STATIC CONST UINT8  gApTrampoline[] = {
%s
};

//
// The trampoline's GDT.  It needs 32-bit descriptors as well as 64-bit ones
// because the mode transition goes real -> protected -> long rather than
// jumping straight from real mode into 64-bit code.
//
STATIC CONST UINT64  gApGdt[5] = {
  0x0000000000000000ULL,   // 0x00 null
  0x00209A0000000000ULL,   // 0x08 code64: present, DPL0, exec/read, L=1
  0x0000920000000000ULL,   // 0x10 data64: present, DPL0, read/write
  0x00CF9A000000FFFFULL,   // 0x18 code32: flat 4 GiB, D=1
  0x00CF92000000FFFFULL    // 0x20 data32: flat 4 GiB
};

/**
  Stamp a page with the trampoline and the values it reads back out of its own
  page.  Shared, so a harness cannot accidentally test a differently-built page.

  @param  Page       Page-aligned page below 1 MiB.
  @param  Cr3        Page tables the AP loads; must be below 4 GiB.
  @param  StackBase  Base of the AP stack array.
  @param  StackSize  Bytes per AP stack.
  @param  Entry      Microsoft-x64 function the AP calls with its slot index.
  @param  StopAt     Halt an AP when it reaches this stage; 0 = never.
**/
STATIC
VOID
HvApStampPage (
  IN UINT8   *Page,
  IN UINT64   Cr3,
  IN UINT64   StackBase,
  IN UINT64   StackSize,
  IN UINT64   Entry,
  IN UINT8    StopAt
  )
{
  ZeroMem (Page, SIZE_4KB);
  CopyMem (Page, gApTrampoline, sizeof (gApTrampoline));
  CopyMem (Page + AP_OFF_GDT, gApGdt, sizeof (gApGdt));

  *(UINT16 *)(Page + AP_OFF_GDTR)     = (UINT16)(sizeof (gApGdt) - 1);
  *(UINT32 *)(Page + AP_OFF_GDTR + 2) = 0;   // base, filled in by the AP itself
  *(UINT64 *)(Page + AP_OFF_CR3)      = Cr3;
  *(UINT64 *)(Page + AP_OFF_STKBASE)  = StackBase;
  *(UINT64 *)(Page + AP_OFF_STKSIZE)  = StackSize;
  *(UINT64 *)(Page + AP_OFF_ENTRY)    = Entry;
  *(UINT64 *)(Page + AP_OFF_SLOT)     = 0;
  *(UINT8  *)(Page + AP_OFF_PROG)     = 0;
  *(UINT8  *)(Page + AP_OFF_STOPAT)   = StopAt;
}

#endif // AP_TRAMPOLINE_H_''' % (defines, len(blob), rows))
